apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-operator
  template:
    metadata:
      labels:
        app: nginx-operator
    spec:
      containers:
        - name: operator
          image: sharathchandra04/sharathchandra04:nginx-operator
          imagePullPolicy: Always
