apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mydeployments-operator-role
rules:
  - apiGroups:
      - "myapps.example.com"
    resources:
      - mydeployments
      - mydeployments/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
